#!/bin/bash
# Generates docs/reference/ from shdoc annotations under src/. Never hand-edit
# the output — see docs/architecture/docs-system.md.

set -eu

mkdir -p docs/reference
# shellcheck disable=SC2016 # literal backticks in printf output, not interpolation
printf '# Shell reference\n\nGenerated by `mise run docs` from shdoc annotations under `src/`.\n\n' >docs/reference/index.md

for f in $(find src -name '*.sh' | sort); do
  rel="${f#src/}"
  out="docs/reference/${rel%.sh}.md"
  mkdir -p "$(dirname "$out")"
  gawk -f scripts/shdoc <"$f" >"$out"
  # shellcheck disable=SC2016 # literal backtick in printf output, not interpolation
  printf -- '- [`%s`](%s)\n' "$rel" "${rel%.sh}.md" >>docs/reference/index.md
done
